geodelabs/geodework-website

app/blog/content/local-ethereum-1.md
app/layout.tsx
app/page.tsx
components/Markdown/Components.tsx
components/Subscribe.tsx
lib/blog.tsx

Deploy `dev` to `main`

---

app/blog/content/local-ethereum-1.md

Beehiiv trackers left in from newsletter, but are inaccurate / not applicable from this source

fix: rm incorrect utm source

---

app/blog/[slug]/page.tsx
app/blog/page.tsx
app/privacy-policy/page.mdx
app/terms-of-use/page.mdx
components/MatomoOptOut.tsx
components/Socials.tsx
components/Subscribe.tsx
styles/clipPaths.ts

- Adds a MatomoOptOut component for user preferences
- Adds to privacy policy and term of use pages
- Refactor clip path styles for better maintainability and consistency
Note: Matomo features not yet added; this prepares codebase for the addition

feat: implement Matomo Opt-Out feature

---

app/layout.tsx
components/Socials.tsx
components/svgs/heart.svg
components/svgs/twitter.svg

- Adds geodework.eth donation link
- Updates social icon

Donate button, social icon update

---

app/terms-of-use/page.mdx

- updated terms of use to include donation policy
- renumbered sections
---
- Please confirm the correct procedure for merging into the main branch.

docs: update terms of use to include donation policy

---

app/terms-of-use/page.mdx

- Revise last updated date in Terms and Conditions

update: revise last updated date in Terms and Conditions

---

app/blog/content/local-ethereum-3.md

- feat: add Taiwan Ethereum Ecosystem Overview blog 3
Source is here: https://localethereum.beehiiv.com/p/taiwan-ethereum-ecosystem-overview

feat: add Taiwan Ethereum Ecosystem Overview #3 article

---

.cursorignore
.vscode/settings.json

- Add config file for cursor and prettier formatting on vscode

Add config file for cursor and prettier formatting on vscode

---

app/donate/page.tsx
lib/constants.ts

- Add Gitcoin donation option to the donate page

Add Gitcoin donation option to the donate page

---

app/blog/content/local-ethereum-3.md
app/blog/content/local-ethereum-4.md

Add New Blog Article 4th

---

app/grant/page.tsx
app/layout.tsx
data/grants.ts
tailwind.config.ts

- Added grants page that showcases grants data imported from `/data/grants.ts`
- Added responsive function introducing `xs` mobile screen size.

Add Grants page

---

app/sitemap.ts
lib/constants.ts

Implemented sitemap generation for static and blog routes to improve SEO.
http://geodework.com/sitemap.xml
should be now accessible

Implement sitemap generation for static and blog routes

---

app/donate/page.tsx
lib/constants.ts

- Added Giveth donation option to the donation page

Add Giveth donation option to the donation page

---

app/donate/page.tsx
app/grants/page.tsx
components/GrantsMain.tsx
data/grants.ts

- Fix projects' links and description in grants
- Updated last updated date
- Separated GrantsMain component to add a dedicated metadata in server side
(Added HeroBackground in donate page as it was left behind unintentionally)

Fix projects' links and description in grants

---

app/layout.tsx
components/AdSense.tsx

Add Google AdSense component for ad integration

Integrate AdSense component into the layout for ad support

---

app/blog/content/argentina-ethereum-ecosystem-overview.md
app/layout.tsx

Add Argentina Ethereum Ecosystem Overview blog article

Add Argentina Ethereum Ecosystem Overview blog article

---

app/blog/content/argentina-ethereum-ecosystem-overview.md
app/blog/page.tsx

- Fixes publish datetime for Argentina post (confirmed via [beehiiv post](https://localethereum.beehiiv.com/p/argentina-ethereum-ecosystem-overview))
- Fixes markdown syntax showing up in blog post preview cards using `sanitizePostPreviewContent`
Production:
PR Fix:

Blog patches

---

app/blog/content/local-ethereum-4.md

- Added Local Ethereum #4 newsletter for a new blog

Add Local Ethereum #4 newsletter for a new blog

---

data/grants.ts

fix: updated date for grants

---

app/blog/content/serbia-ethereum-ecosystem-overview.md

A new blog post for https://localethereum.beehiiv.com/p/serbia-ethereum-ecosystem-overview

Add Serbia Ethereum Ecosystem Overview blog post

---

app/blog/content/poland-ethereum-ecosystem-overview.md

Remove outdated announcements from Poland Ethereum Ecosystem Overview Blog Post

Remove outdated announcements from Poland Ethereum Ecosystem Overview Blog Post

---

app/blog/content/local-ethereum-5.md
app/blog/content/local-ethereum-6.md

Add Local Ethereum #6 newsletter blog article
https://localethereum.beehiiv.com/p/local-ethereum-6

 Add Local Ethereum #6 newsletter blog article

---

app/blog/partial/footer.md

- Fix Subscription Link in Blog Footer Page

Fix Subscription Link in Blog Footer Page

---

app/blog/content/india-ethereum-eocsystem-overview.md
app/blog/content/local-ethereum-8.md
app/blog/page.tsx
components/Markdown/Provider.tsx
mdx-components.tsx

Summary:
- Hooked MarkdownProvider into the MDX component map so blog posts inherit the shared typography overrides.
- Tweaked MDX heading spacing and list indentation to improve readability.
- Normalized bold subsection labels and citation text in the India ecosystem and Local Ethereum issue 8 markdown files.
- Dropped an unused constant import from the blog index page.

refactor: adjust md format and styles

---

app/blog/content/brazil-ethereum-ecosystem-overview.md
app/blog/partial/footer.md
components/Markdown/Components.tsx

Summary:
- Adjust `em` markdown component font-size and alignment
- Adjust `footer` spacing and layout
- Add `Brazil Ethereum Ecosystem Overview` blog

feat: add brazil blog post
